workflows:

  ios-workflow:

    name: iOS Workflow

    max_build_duration: 120

    environment:

      ios_signing:

        distribution_type: ad_hoc

        bundle_identifier: com.akshayra.flutterPipeline

      vars:

      flutter: 3.24.5

      xcode: latest

      cocoapods: default

    scripts:

      - name: Set up code signing settings on Xcode project

        script: xcode-project use-profiles

      - name: Get Flutter packages

        script: flutter packages pub get

      - name: Install pods

        script: find . -name "Podfile" -execdir pod install \;

      - name: Flutter build ipa and automatic versioning

        script: |

          flutter build ipa --release \

            --build-name=1.0.0 \

            --export-options-plist=ios/Runner/export-options.plist          

    artifacts:

      - build/ios/ipa/*.ipa

      - /tmp/xcodebuild_logs/*.log

      - flutter_drive.log

