workflows:
  ios:
    name: iOS Build Workflow
    max_build_duration: 60
    instance_type: macos-latest
    environment:
      vars:
        # Set environment variables here, e.g., Flutter version, build modes, etc.
        FLUTTER_VERSION: stable
        BUILD_MODE: release
    triggers:
      - event: push
        branch: flutter-sample
    pre_cache:
      paths:
        - .pub-cache
        - ios/Pods
    cache:
      paths:
        - .pub-cache
        - ios/Pods
    scripts:
      - name: Install Flutter SDK
        script: |
          git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION
          export PATH="$PATH:`pwd`/flutter/bin"
      - name: Install Dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build iOS App
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
